#!/bin/bash

DEST=/home/mcnuggetsx20/Documents/repos/linux-thinkpad
USR=/home/mcnuggetsx20
DATE=$(date "+%d %b %Y %H:%M:%S")

cp /bin/configpush ${DEST}/bin
cp -r ${USR}/.config/qtile ${DEST}/.config
cp -r ${USR}/.config/alacritty ${DEST}/.config
cp -r ${USR}/.config/nvim ${DEST}/.config
cp -r ${USR}/.bashrc ${DEST}

cd $DEST
git add -A
git commit -m "${DATE}"
git push


